name: ci

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: jubilee2
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm/v7
          push: true
          tags: jubilee2/rpi-gitlab-ce:${{steps.tag.outputs.tag}}
          cache-from: type=registry,ref=jubilee2/rpi-gitlab-ce:nightly
          cache-to: type=inline

