name: docker-image-nightly

on: [push, pull_request]

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: jubilee2
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm/v7
          push: true
          tags: jubilee2/rpi-gitlab-ce:nightly
          cache-from: type=registry,ref=jubilee2/rpi-gitlab-ce:nightly
          cache-to: type=inline

